version: '2'
services:
  apache-flink-batch-jobs:
   image: apache-flink-batch-jobs:latest
   container_name: apache-flink-batch-jobs
   entrypoint: ["/submit.sh"]
   volumes:
     - ./result:/usr/src/app/result
     - ./data:/usr/src/app/data
   ports:
     - "8080:8080"
     - "8081:8081"